<!DOCTYPE html>
<html lang="en">

<!-- header section -->
<?php include 'header.php';?>

<body>
	
<!-- navigation -->

	<div class="container">
		<div class="navbar navbar-default navbar-static-top" role="navigation">
		<div class="navbar-header">
			<a href="#" class="navbar-brand"><img src="/images/hiprc2.png " width="115" border="0" class="img-responsive"  alt="logo"></a>
		</div>
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><a href="../index.php">HOME</a></li>
				<li><a href="about.php">PEOPLE</a></li>
				<li><a href="projects.php">PROJECTS</a></li>
				<li><a href="tools.php">TOOLS</a></li>
				<li><a href="../contact.php">CONTACT US</a></li>
			</ul>
		</div>
	</div>
</div>			



	<div class="container text-center rounded_rectangle">
		<div class="row" style="padding:15px">
			<!-- <div class="col-md-12 col-sm-12"> -->
			<div class="hero-unit">
				<h1><span> An automated building thermal model generator and HVAC control performance simulation tool</span></h1>
			</div>
			<!-- </div> -->
		</div>
		<div class="row" style="padding:15px">
			<img class="one" src="/images/toolflow.jpeg" width="700" height="400" alt="HVAC">
		</div>
		<div class="row topic-desc" style="padding:15px">
			<p><span>

				Note: The tool is in developing phase and constantly updated for in house experiments. The latest version of the tool will be available on request(mailto:rajib.jana@cse.iitkgp.ernet.in, cc:jlrajib.cse@gmail.com). In order to get the flavour of allocation-aware HVAC control synthesis, reader can download the <a href="/images/tarball.zip" download ="tarball.zip">tarball</a> which contains final output files generated by the tool for given inputs. The output file (simulation.py) is required to execute for analyzing the HVAC performance. The necessary information to execute the file is mentioned in <a href="/images/readme.pdf" download ="readme.pdf">readMe file</a>.

				</span></p>
		</div>
		<br>
			<hr class="divider-line">
	</div>
	</div>


							
								
								
								
							
								

<!-- footer section -->
<?php include 'footer.php';?>

<!-- javascript js -->	
<script src="js/jquery.js"></script>
<script src="js/bootstrap.min.js"></script>	
<script src="js/nivo-lightbox.min.js"></script>
<script src="js/custom.js"></script>

</body>
</html>
