# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            My Place
tagline:          "Sunandan's Home"
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://SunandanAdhikary.github.io
baseurl:          /

author:
  name:           'Sunanan Adhikary'
  url:            https://twitter.com/mesunandan

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/SunandanAdhikary
